### ISSUE TITLE
Water tap heating not chaging mode

### ISSUE THREAD

**Issue by bruvv** [wmalgadey/PyTado#9]
When I use the heating it works fine when I want to do the same for the water tap it does not work.
```
- id: '1545245312247'
  alias: Verwarming uit
  trigger:
  - entity_id: sensor.huiskamer_tado_mode
    platform: state
    to: AWAY
  condition: []
  action:
  - entity_id: climate.huiskamer
    service: climate.set_operation_mode
    data:
      operation_mode: Off
  - entity_id:  climate.warm_water
    service: climate.set_operation_mode
    data:
      operation_mode: Off
```
That is what I use.
